set1={"apple","banana","cherry"}
print(set1)
set1.add("mango")
"""print(set1)
set1.clear()"""
print(set1)
set1.copy()
print(set1)
set1.discard("cherry")
print(set1)
set2={"india","japan","uk"}
z=set1.isdisjoint(set2)
print(z)
set1={"apple","banana","cherry"}
set2={"india","japan","apple"}
z=set1.intersection(set2)
print(z)
z=set1.difference(set2)
print(z)
z=set1.union(set2)
print(z)
set1={"apple","banana","cherry"}
set2={"india","banana","apple","japan","cherry"}
z=set1.issubset(set2)
print(z)
set1.update(set2)
print(set1)
