a="welcome to DYPCET T.Y C,kolhapur 2024-2025 batch"
print(a)
print(a[0:7])
print(a[-8:])
print(a.capitalize())
print(a.casefold())
print(a.center(6))
print(a.count('o'))
print(a.isdigit())
print(a.isidentifier())
print(a.lstrip())
print(a.join('s'))
print(a.rfind('to'))
print(a.rpartition('CET'))
print(a.replace("to","in"))
print(a.rindex("C"))
print(len(a))
print(a.zfill(1))
