tuple1=("neha","diksha","swara","neha")
tuple2 = (0, 1, 2, 3, 2, 3, 1, 3, 2) 
res = tuple2.count(3) 
print('Count of 3 in tuple1 is:', res) 
res = tuple1.count('neha') 
print('Count of neha in tuple1:', res)
z=tuple1.index("diksha")
print(z)
z=tuple2.index(3)
print(z)
print(len(tuple1))
