# file=open("example.txt",'w')
# print("The file has been created")

# file=open("example.txt",'w')
# print(file.write("this is the example file.\n"))
# print(file.write("My name is neha.\n"))
# print(file.write("I am from satara.\n"))
# print(file.write("I am studying in dypcet.\n"))
# print(file.write("I am in third year."))

# print(file.read())
# print(file.read(20))
# file=open("example.txt",'r')
# line=file.readline()
# print("\nread a single line:")
# print(line)
# file=open("example.txt",'r')
# line=file.readlines()
# print("read all lines as a list\n")
# print(line)
file=open("example.txt",'a')
file.write('i am in CSE branch:\n')
print("data appended in file")
